### ISSUE TITLE
Set nominal units to S_nt

### ISSUE THREAD

**Issue by balazskertesz** [korenmiklos/impvol-julia#11]
during free trade phase, we calculate with shares, then the eq. algorithm somehow falls back to using nominal (in terms of USD) units

**Comment by korenmiklos** [comment]
Our nominal anchor is that all sectoral prices are 1 in the US in 1972: `p_sectoral[:,end,:,1] = 1.0`. Make this compatible with `S_nt`

**Comment by korenmiklos** [comment]
@balazskertesz What is `z` for US? How do we calibrate it?

**Comment by korenmiklos** [comment]
Please convert `S_nt` to 1972 US dollars. Use the same units as `sectoral_value_added`.
